In [6]:
import numpy as np
import pandas as pd
import altair as alt
import holoviews as hv


In [20]:
entropy = lambda a: -(a * np.log(a)).sum()

In [21]:
hilf = lambda a: (a**2).sum()

In [22]:
_xs = np.linspace(1,10,100)
xs = _xs / _xs.sum()

In [23]:
_df = pd.DataFrame({'ent': entropy(xs), 'x': xs, 'hilf': hilf(xs) })

In [24]:
base = alt.Chart(_df).mark_point().encode(
    x= 'x:Q')
base.encode(y='ent') + base.encode(y='hilf')

alt.LayerChart(...)

In [27]:
x = np.array([71, 26, 67])

In [32]:
d = np.array([30, 10, 20])

In [29]:
M = np.array([[0.2, 0, 0.4], [0, 0.1, 0.2], [0.4, 0.2, 0.2]])

In [33]:
(np.eye(3) - M).in

AttributeError: 'numpy.ndarray' object has no attribute 'inv'

In [45]:
x = np.linalg.inv(np.eye(3) - M) @ d
x

array([71., 26., 67.])

$$x = (I-M)^{-i} d$$ or $$x - Mx = d$$ 

In [47]:
x

array([71., 26., 67.])

In [46]:
x - M@x

array([30., 10., 20.])

In [49]:
out2 = np.array([23, 16, 22])
in2 = np.linalg.inv(np.eye(3) - M) @ out2
in2

array([62.1, 32.6, 66.7])